services:
    mosquitto:
        image: eclipse-mosquitto:2
        ports:
            - 1883:1883
            - 8883:8883
            - 9001:9001
        volumes:
            - ./config/:/mosquitto/config
            - ./data/:/mosquitto/data
        networks:
            mosquitto:
                ipv4_address: 10.5.0.5
networks:
    mosquitto:
        name: mosquitto
        driver: bridge  
        ipam:
            config:
                -   subnet: 10.5.0.0/16
                    gateway: 10.5.0.1